DL is deprecated, please use Fiddle
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/mysql2-0.3.16/lib/mysql2/error.rb:22: warning: method redefined; discarding old sql_state=
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/version.rb:5: warning: loading in progress, circular require considered harmful - c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb
	from c:/Ruby/Ruby200/bin/rspec:23:in `<main>'
	from c:/Ruby/Ruby200/bin/rspec:23:in `load'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `<top (required)>'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `require'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `<top (required)>'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `require'
	from d:/sites/key_manager/config/environment.rb:2:in `<top (required)>'
	from d:/sites/key_manager/config/environment.rb:2:in `require'
	from d:/sites/key_manager/config/application.rb:7:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:9:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:9:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/version.rb:5:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/version.rb:5:in `require'
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/node.rb:73: warning: method redefined; discarding old children=
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:197: warning: literal in condition
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:8: warning: loading in progress, circular require considered harmful - c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb
	from c:/Ruby/Ruby200/bin/rspec:23:in `<main>'
	from c:/Ruby/Ruby200/bin/rspec:23:in `load'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `<top (required)>'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `require'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `<top (required)>'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `require'
	from d:/sites/key_manager/config/environment.rb:2:in `<top (required)>'
	from d:/sites/key_manager/config/environment.rb:2:in `require'
	from d:/sites/key_manager/config/application.rb:7:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:7:in `<module:Script>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:8:in `<class:Literal>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:8:in `require'
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/number.rb:1: warning: loading in progress, circular require considered harmful - c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb
	from c:/Ruby/Ruby200/bin/rspec:23:in `<main>'
	from c:/Ruby/Ruby200/bin/rspec:23:in `load'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `<top (required)>'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `require'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `<top (required)>'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `require'
	from d:/sites/key_manager/config/environment.rb:2:in `<top (required)>'
	from d:/sites/key_manager/config/environment.rb:2:in `require'
	from d:/sites/key_manager/config/application.rb:7:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:7:in `<module:Script>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:9:in `<class:Literal>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:9:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/number.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/number.rb:1:in `require'
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/color.rb:1: warning: loading in progress, circular require considered harmful - c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb
	from c:/Ruby/Ruby200/bin/rspec:23:in `<main>'
	from c:/Ruby/Ruby200/bin/rspec:23:in `load'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `<top (required)>'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `require'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `<top (required)>'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `require'
	from d:/sites/key_manager/config/environment.rb:2:in `<top (required)>'
	from d:/sites/key_manager/config/environment.rb:2:in `require'
	from d:/sites/key_manager/config/application.rb:7:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:7:in `<module:Script>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:10:in `<class:Literal>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:10:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/color.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/color.rb:1:in `require'
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/bool.rb:1: warning: loading in progress, circular require considered harmful - c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb
	from c:/Ruby/Ruby200/bin/rspec:23:in `<main>'
	from c:/Ruby/Ruby200/bin/rspec:23:in `load'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `<top (required)>'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `require'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `<top (required)>'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `require'
	from d:/sites/key_manager/config/environment.rb:2:in `<top (required)>'
	from d:/sites/key_manager/config/environment.rb:2:in `require'
	from d:/sites/key_manager/config/application.rb:7:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:7:in `<module:Script>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:11:in `<class:Literal>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:11:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/bool.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/bool.rb:1:in `require'
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/null.rb:1: warning: loading in progress, circular require considered harmful - c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb
	from c:/Ruby/Ruby200/bin/rspec:23:in `<main>'
	from c:/Ruby/Ruby200/bin/rspec:23:in `load'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `<top (required)>'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `require'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `<top (required)>'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `require'
	from d:/sites/key_manager/config/environment.rb:2:in `<top (required)>'
	from d:/sites/key_manager/config/environment.rb:2:in `require'
	from d:/sites/key_manager/config/application.rb:7:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass-rails.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails.rb:8:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/helpers.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_functions.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass.rb:93:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:40:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script.rb:4:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/operation.rb:2:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/string.rb:1:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:7:in `<module:Script>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:12:in `<class:Literal>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/literal.rb:12:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/null.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/null.rb:1:in `require'
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/parser.rb:265: warning: literal in condition
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/script/parser.rb:278: warning: literal in condition
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/scss/rx.rb:101: warning: character class has duplicated range
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/scss/rx.rb:114: warning: character class has duplicated range
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/scss/rx.rb:115: warning: character class has duplicated range
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/scss/rx.rb:128: warning: character class has duplicated range
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:444: warning: literal in condition
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:671: warning: literal in condition
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/scss/static_parser.rb:31: warning: literal in condition
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/importer.rb:23: warning: method redefined; discarding old find_relative
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_importer.rb:13: warning: previous definition of find_relative was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/importer.rb:31: warning: method redefined; discarding old find
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_importer.rb:21: warning: previous definition of find was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sass-rails-4.0.3/lib/sass/rails/template.rb:5: warning: method redefined; discarding old evaluate
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.11.0/lib/sprockets/sass_template.rb:36: warning: previous definition of evaluate was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/warden-1.2.3/lib/warden/proxy.rb:72: warning: assigned but unused variable - opts
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/warden-1.2.3/lib/warden/proxy.rb:104: warning: assigned but unused variable - opts
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:22: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/devise-3.2.4/lib/devise/rails/warden_compat.rb:2: warning: method redefined; discarding old request
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/warden-1.2.3/lib/warden/mixins/common.rb:17: warning: previous definition of request was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/devise-3.2.4/lib/devise/rails/warden_compat.rb:11: warning: method redefined; discarding old reset_session!
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/warden-1.2.3/lib/warden/mixins/common.rb:38: warning: previous definition of reset_session! was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/cancan-1.6.10/lib/cancan/rule.rb:131: warning: assigned but unused variable - child
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/cancan-1.6.10/lib/cancan/model_adapters/active_record_adapter.rb:71: warning: shadowing outer local variable - nested
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/cancan-1.6.10/lib/cancan/model_adapters/active_record_adapter.rb:122: warning: shadowing outer local variable - rule
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client.rb:468: warning: assigned but unused variable - cols
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client.rb:708: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client.rb:815: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client/filter.rb:54: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/configuration/searchd.rb:25: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/configuration/searchd.rb:25: warning: method redefined; discarding old snippets_file_prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/configuration/searchd.rb:25: warning: method redefined; discarding old snippets_file_prefix=
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/configuration/sql_source.rb:21: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/configuration/tsv_source.rb:8: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/configuration/xml_source.rb:13: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/query.rb:102: warning: character class has duplicated range: /[\(\)\|\-!@~\/"\/\^\$\\><&=]/
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/query/select.rb:220: warning: shadowing outer local variable - value
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/client.rb:28: warning: shadowing outer local variable - index
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/client.rb:40: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/client.rb:7: warning: method redefined; discarding old initialise_connection
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client.rb:556: warning: previous definition of initialise_connection was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/client.rb:23: warning: method redefined; discarding old update_message
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client.rb:806: warning: previous definition of update_message was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/client/filter.rb:11: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/client/filter.rb:6: warning: method redefined; discarding old append_integer_range
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client/filter.rb:47: warning: previous definition of append_integer_range was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/client/filter.rb:10: warning: method redefined; discarding old append_array
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client/filter.rb:53: warning: previous definition of append_array was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/0.9.9/configuration/searchd.rb:4: warning: method redefined; discarding old valid?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/configuration/searchd.rb:38: warning: previous definition of valid? was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/1.10/client.rb:8: warning: method redefined; discarding old excerpts_message
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/riddle-1.5.11/lib/riddle/client.rb:786: warning: previous definition of excerpts_message was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/batched_search.rb:12: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/batched_search.rb:20: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration/distributed_indices.rb:22: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration/distributed_indices.rb:27: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration/distributed_indices.rb:14: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/configuration/minimum_fields.rb:18: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/connection.rb:75: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/connection.rb:86: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/connection.rb:108: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/deletion.rb:11: warning: assigned but unused variable - error
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/deletion.rb:21: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/deletion.rb:21: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/facet_search.rb:99: warning: assigned but unused variable - limit
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/float_formatter.rb:16: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/index_set.rb:43: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/index_set.rb:22: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/index_set.rb:22: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/index_set.rb:22: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/masks/pagination_mask.rb:58: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/middleware.rb:8: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/middleware.rb:8: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/active_record_translator.rb:31: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/geographer.rb:30: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/geographer.rb:59: warning: method redefined; discarding old latitude
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/geographer.rb:63: warning: method redefined; discarding old longitude
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/geographer.rb:69: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/glazier.rb:30: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/inquirer.rb:60: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/sphinxql.rb:200: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/sphinxql.rb:248: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/sphinxql.rb:31: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/middlewares/stale_id_checker.rb:25: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/search/batch_inquirer.rb:17: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/search/glaze.rb:30: warning: shadowing outer local variable - pane
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/test.rb:52: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/wildcard.rb:33: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/wildcard.rb:33: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/joiner-0.3.0/lib/joiner/path.rb:22: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/joiner-0.3.0/lib/joiner/path.rb:22: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/association_proxy/attribute_finder.rb:33: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/association_proxy/attribute_matcher.rb:38: warning: mismatched indentations at 'end' with 'class' at 1
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/association_proxy/attribute_matcher.rb:14: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/association_proxy/attribute_matcher.rb:14: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/attribute/type.rb:30: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/attribute/type.rb:30: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/attribute/values.rb:7: warning: shadowing outer local variable - object
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/base.rb:45: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/column.rb:19: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/column_sql_presenter.rb:21: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/column_sql_presenter.rb:21: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/column_sql_presenter.rb:21: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/column_sql_presenter.rb:21: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/index.rb:4: warning: method redefined; discarding old reference
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/index.rb:5: warning: method redefined; discarding old definition_block=
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/interpreter.rb:6: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/polymorpher.rb:13: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/polymorpher.rb:13: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/polymorpher.rb:13: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/property_query.rb:64: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/property_query.rb:25: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/property_query.rb:25: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/property_query.rb:25: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/property_sql_presenter.rb:25: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/statement.rb:113: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/clause_builder.rb:9: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/clause_builder.rb:24: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_builder/query.rb:42: warning: `*' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/sql_source.rb:131: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb:37: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb:49: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/active_record/callbacks/update_callbacks.rb:51: warning: assigned but unused variable - error
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/deltas/delete_job.rb:12: warning: assigned but unused variable - error
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/real_time/property.rb:19: warning: shadowing outer local variable - base
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/real_time/index.rb:82: warning: `&' interpreted as argument prefix
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/real_time/populator.rb:26: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/real_time/transcriber.rb:27: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/real_time/callbacks/real_time_callbacks.rb:18: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/thinking-sphinx-3.1.1/lib/thinking_sphinx/real_time/callbacks/real_time_callbacks.rb:18: warning: private attribute?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/strong_password-0.0.4/lib/strong_password/nist_bonus_bits.rb:41: warning: mismatched indentations at 'end' with 'if' at 37
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/strong_password-0.0.4/lib/strong_password/nist_bonus_bits.rb:43: warning: mismatched indentations at 'end' with 'def' at 17
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/strong_password-0.0.4/lib/strong_password/dictionary_adjuster.rb:995: warning: shadowing outer local variable - min_entropy
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247: warning: loading in progress, circular require considered harmful - c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/strong_password-0.0.4/lib/strong_password.rb
	from c:/Ruby/Ruby200/bin/rspec:23:in `<main>'
	from c:/Ruby/Ruby200/bin/rspec:23:in `load'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `<top (required)>'
	from d:/sites/key_manager/spec/controllers/categories_controller_spec.rb:1:in `require'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `<top (required)>'
	from d:/sites/key_manager/spec/rails_helper.rb:4:in `require'
	from d:/sites/key_manager/config/environment.rb:2:in `<top (required)>'
	from d:/sites/key_manager/config/environment.rb:2:in `require'
	from d:/sites/key_manager/config/application.rb:7:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler.rb:132:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:61:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:72:in `each'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:76:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/strong_password-0.0.4/lib/strong_password.rb:10:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/strong_password-0.0.4/lib/active_model/validations/password_strength_validator.rb:1:in `<top (required)>'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
	from c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
mechanize/cookie will be deprecated.  Please migrate to the http-cookie APIs.
mechanize/cookie_jar will be deprecated.  Please migrate to the http-cookie APIs.
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/directory.rb:7: warning: assigned but unused variable - search_range
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/directory.rb:8: warning: assigned but unused variable - entry_selector
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/directory.rb:8: warning: assigned but unused variable - range_shift
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/resource_file.rb:15: warning: assigned but unused variable - data_length
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/cmap/format00.rb:47: warning: assigned but unused variable - length
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/cmap/format06.rb:40: warning: assigned but unused variable - length
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/cmap/format10.rb:40: warning: assigned but unused variable - length
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/cmap/format12.rb:51: warning: assigned but unused variable - length
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/kern/format0.rb:15: warning: assigned but unused variable - search_range
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/kern/format0.rb:15: warning: assigned but unused variable - entry_selector
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/kern/format0.rb:15: warning: assigned but unused variable - range_shift
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/name.rb:56: warning: assigned but unused variable - id
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/name.rb:79: warning: assigned but unused variable - format
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/post.rb:66: warning: assigned but unused variable - end_of_table
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/table/post/format25.rb:17: warning: assigned but unused variable - number_of_glyphs
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/ttfunk-1.2.0/lib/ttfunk/subset/base.rb:34: warning: assigned but unused variable - code
d:/sites/key_manager/config/initializers/bypass_ssl_verification_for_open_uri.rb:1: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/devise-3.2.4/lib/devise/rails.rb:50: warning: method redefined; discarding old respond_to?
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/actionpack-4.1.4/lib/action_dispatch/routing/routes_proxy.rb:21: warning: previous definition of respond_to? was here
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/mail-2.5.4/lib/mail/network/delivery_methods/sendmail.rb:53: warning: shadowing outer local variable - to
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/devise-3.2.4/lib/devise/failure_app.rb:25: warning: method redefined; discarding old default_url_options
c:/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.1.4/lib/active_support/core_ext/class/attribute.rb:86: warning: previous definition of default_url_options was here
No examples found.


Finished in 0 seconds (files took 32.16 seconds to load)
0 examples, 0 failures
