# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94730841d80e811de49fdb8ab9ed378fd46c251b847ecf81736bc4075b32f6c86ec124eeca647cbef0483aa624c0239e835600e8d6639238901c41bde606aee3

test:
  secret_key_base: 26400b050b69a3ae3297c7f37537861c5699b80d4c2503395cbabbdb710caf3f9b4816a11da5d43fb52737fce3ede2b79f92566f726d9ca8df276411ed2c122e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
